export enum ForumActionsTypes {
 FORUM_LOADING = 'FORUM_LOADING',
 FORUM_INIT = 'FORUM_INIT',
 //  ----------------------------------------------- AUTH
 USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
 USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
 USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
 USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED',

 USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS',
 USER_REGISTER_FAILED = 'USER_REGISTER_FAILED',
 //  -----------------------------------------------
 FORUM_CATEGORIES_STATE_CHANGE = 'FORUM_CATEGORIES_STATE_CHANGE',
}

export enum AlertActionsTypes {
 SET_ALERT = 'SET_ALERT',
 REMOVE_ALERT = 'REMOVE_ALERT',
}

export enum CategoriesActionsTypes {
 CATEGORIES_LOADING = 'CATEGORIES_LOADING',
 //  ----------------------------------------------- CATEGORIES
 CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS',
 CATEGORIES_FETCH_FAILED = 'CATEGORIES_FETCH_FAILED',
 //  ----------------------------------------------- CATEGORY
 CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS',
 CATEGORY_FETCH_FAILED = 'CATEGORY_FETCH_FAILED',
 CATEGORY_SELECT = 'CATEGORY_SELECT',
}
